version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-db-container
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "johndoe"
      POSTGRES_PASSWORD: "randompassword"
      POSTGRES_DB: "datacakra-be-test"
  pgadmin:
    container_name: pgadmin4-container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80